# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [12]:
# Import torch
import torch
torch.rand(7,7)

# Create random tensor


tensor([[0.1005, 0.0797, 0.4411, 0.6821, 0.7285, 0.0233, 0.7715],
        [0.1834, 0.6155, 0.2324, 0.7221, 0.5551, 0.5485, 0.2538],
        [0.2940, 0.1536, 0.0575, 0.7300, 0.3017, 0.5610, 0.0628],
        [0.2549, 0.7525, 0.7928, 0.7020, 0.5071, 0.3682, 0.8258],
        [0.2980, 0.6232, 0.4510, 0.1519, 0.8984, 0.8992, 0.2161],
        [0.1496, 0.8471, 0.2236, 0.6510, 0.0486, 0.0660, 0.8198],
        [0.0041, 0.1680, 0.1362, 0.7856, 0.1627, 0.1244, 0.0116]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [13]:
# Create another random tensor
tensor_a= torch.rand(1,7)
tensor_b= torch.rand(1,7)

# Perform matrix multiplication
torch.matmul(tensor_a,tensor_b.T)

tensor([[1.0492]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [17]:
malual_seed = 0

# Create two random tensors
torch.manual_seed(malual_seed)
tensor_a= torch.rand(7,7)
tensor_b= torch.rand(1,7)

# Matrix multiply tensors
torch.matmul(tensor_a,tensor_b.T)

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [5]:
# Set random seed on the GPU


In [18]:
if torch.cuda.is_available():
    # Set the GPU random seed
    torch.cuda.manual_seed(1234)
    print("GPU random seed set to 1234.")
else:
    print("No GPU available. Cannot set GPU random seed.")

No GPU available. Cannot set GPU random seed.



### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [19]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU, if not, use CPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")

# Create two random tensors on the chosen device
tensor_A_gpu = torch.rand(2, 3).to(device)
tensor_B_gpu = torch.rand(2, 3).to(device)

print(tensor_A_gpu, tensor_A_gpu.shape)
print(tensor_B_gpu, tensor_B_gpu.shape)

Device: cpu
tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]]) torch.Size([2, 3])
tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]]) torch.Size([2, 3])



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [20]:
# Perform matmul on tensor_A and tensor_B
torch.matmul(tensor_A_gpu,tensor_B_gpu.T)

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]])

### 8. Find the maximum and minimum values of the output of 7.

In [23]:
# Perform matmul to get the output from problem 7
matmul_result = torch.matmul(tensor_A_gpu,tensor_B_gpu.T)

# Find max of the matmul result
max_value = torch.max(matmul_result)
print(f"Maximum value: {max_value}")

# Find min of the matmul result
min_value = torch.min(matmul_result)
print(f"Minimum value: {min_value}")

Maximum value: 0.5617256760597229
Minimum value: 0.3647301495075226


### 9. Find the maximum and minimum index values of the output of 7.

In [25]:
# Find arg max
max_index= torch.argmax(matmul_result)
print(f"Maximum index: {max_index}")
# Find arg min
min_index= torch.argmin(matmul_result)
print(f"Minimum index: {min_index}")


Maximum index: 3
Minimum index: 0



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [26]:
# Set seed
torch.manual_seed(7)
# Create random tensor
tensor = torch.rand(1, 1, 1, 10)
print(tensor, tensor.shape)

# Remove single dimensions
squeezed_tensor = tensor.squeeze()
print(squeezed_tensor, squeezed_tensor.shape)

# Print out tensors and their shapes
print(tensor, tensor.shape)
print(squeezed_tensor, squeezed_tensor.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])


In [27]:
# Example to demonstrate torch.squeeze() with non-consecutive '1' dimensions

# Create a tensor with shape [1, 2, 7, 1, 4, 1]
example_tensor = torch.randn(1, 2, 7, 1, 4, 1)
print(f"Original tensor shape: {example_tensor.shape}")

# Squeeze the tensor
squeezed_example_tensor = example_tensor.squeeze()
print(f"Squeezed tensor shape: {squeezed_example_tensor.shape}")

# You can see that all dimensions of size 1 are removed, regardless of their position.

Original tensor shape: torch.Size([1, 2, 7, 1, 4, 1])
Squeezed tensor shape: torch.Size([2, 7, 4])
